@host = http://{{$dotenv APP_URL}}
@port = {{$dotenv APP_PORT}}

### Metodos GET
GET {{host}}:{{port}}/controles

###
POST {{host}}:{{port}}/controles/
Content-Type: application/json

{
  "macnumber": "AC0BFBCF8138",
  "imei": "864764033677903"
}

### Cambiar numero mac
PUT {{host}}:{{port}}/controles/21
Content-Type: application/json

{
  "macnumber": "acarolhff"
}


### Cambiar estado del control
PUT {{host}}:{{port}}/controles/active
Content-Type: application/json

{
  "id": "27"
}

### Raiz
GET {{host}}:{{port}}
