@host = http://{{$dotenv APP_URL}}
@port = {{$dotenv APP_PORT}}
@url = {{host}}:{{port}}

### Obtiene todos lo registros
GET {{url}}/dato

### Obtiene solo los registros con id
GET {{url}}/dato/id?id=2&lost=45

### Metodos POST
#Crea un registro
POST {{url}}/dato
Content-Type: application/json

{
  "siw": 65,
  "sig": 20,
  "te": 25.3,
  "r1": true,
  "r2": false,
  "err": 0
}